openapi: 3.0.3
info:
  title: gm98backend-Api
  description: GM9988後台 API
  version: 1.0.0
servers:
- url: /
  description: default root url
- url: http://gm98ba.ateam99.net/
  description: Development server non-https
- url: https://gm98ba.ateam99.net/
  description: Development server https
tags:
- name: login method
  description: login
- name: Role method
  description: role
paths:
  /api/login:
    post:
      tags:
        - login method
      summary: user login
      description: user login
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                username:
                  description: username
                  type: string
                password:
                  description: password
                  type: string
              type: object
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                properties:
                  data:
                    properties:
                      user:
                        description: user data
                        properties:
                          identity:
                            description: identity
                            type: string
                          username:
                            description: username
                            type: string
                          nickname:
                            description: nickname
                            type: string
                          image:
                            description: image
                            type: string
                        type: object
                    type: object
                  token:
                    description: token
                    type: string
                type: object
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unprocessableEntity'
        500:
          description: ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'
      security:
        - Bearer: []
  /api/role:
    get:
      tags:
      - Role method
      summary: Get Role List
      security:
        - Bearer: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/roleList'
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unprocessableEntity'
        500:
          description: ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'
    post:
      tags:
        - Role method
      summary: Create Role
      security:
        - Bearer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createRole'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    description: success
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unprocessableEntity'
        500:
          description: ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'
  /api/role/{roleId}:
    get:
      tags:
      - Role method
      description: Get Role permission list
      summary: Get Role permission list
      parameters:
      - name: roleId
        in: path
        description: role ID
        required: true
        schema:
          type: integer
          format: int64
      security:
        - Bearer: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rolePermissionList'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unprocessableEntity'
        '500':
          description: ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'
components:
  schemas:
    badRequest:
      properties:
        error:
          description: 錯誤訊息
          type: string
      type: object
    unprocessableEntity:
      oneOf:
        - properties:
            error:
              description: validate error
              type: object
              allOf:
                - properties:
                    column_name:
                      type: array
                      items:
                        type: string
                  type: object
          type: object
        - properties:
            error:
              description: validate error
              type: string
          type: object
    serverError:
      properties:
        error:
          description: 錯誤訊息
          type: string
      type: object
    roleList:
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                description: ID
              name:
                type: string
                description: Role name
      type: object
    rolePermissionList:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              permission_id:
                type: integer
                description: permission ID
              name:
                type: string
                description: permission name
              status:
                type: integer
                description: 是否開啟
              children:
                type: array
                items:
                  - []
    createRole:
      type: object
      properties:
        name:
          type: string
          description: 角色名稱
        permissionids:
          description: 權限 IDs
          type: array
          items:
            type: integer
  securitySchemes:
    Bearer:
      type: http
      name: Authorization
      in: header
      bearerFormat: "JWT"
      scheme: "bearer"
